### ISSUE TITLE
Nitro Like Profiles Does not work

### ISSUE THREAD

**Issue by Sebastianroczz** [DaBluLite/css-snippets#1]
![Screenshot 2023-07-03 103623](https://github.com/DaBluLite/css-snippets/assets/132775390/c620db02-4d91-477f-bd1a-915ce576d418)
![Screenshot 2023-07-03 104107](https://github.com/DaBluLite/css-snippets/assets/132775390/7de1c36d-7dfa-4b68-8bfc-e776c9fdeba4)

**Comment by Sebastianroczz** [comment]
am i doing something wrong?

**Comment by Sebastianroczz** [comment]
also before you say anything i tried using it without themes

**Comment by Sebastianroczz** [comment]
yes i pressed the update button and the other ones work

**Comment by DaBluLite** [comment]
![image](https://github.com/DaBluLite/css-snippets/assets/73998678/cfad0750-2633-435e-ac04-793d610992cf)
the snippet is working perfectly fine, it's also working for you. this is how it's meant to look

**Comment by DaBluLite** [comment]
I'm closing this due to lack of response.

**Comment by Sebastianroczz** [comment]
i thought it was going to look like this??? 
![image](https://github.com/DaBluLite/css-snippets/assets/132775390/81ebbc08-07fe-4821-bddc-37ec6049866f)

**Comment by DaBluLite** [comment]
That is how they look on Default Discord, with a Nitro theme. You can always change the default colors yourself, and create your own gradients

**Comment by Sebastianroczz** [comment]
oh ok thank you!

**Comment by Sebastianroczz** [comment]
im a noob at coding so how exactly would I do that?

**Comment by DaBluLite** [comment]
```css
:root {
    --nitrolike-profile-primary: var(--background-primary);
    --nitrolike-profile-secondary: var(--background-primary);
    --nitrolike-profile-gradient: var(--bg-overlay-app-frame,var(--nitrolike-profile-gradient-default));
    --nitrolike-profile-gradient-default: linear-gradient(var(--nitrolike-profile-primary),var(--nitrolike-profile-secondary));
}
```
These are the variables you can change, you can even create your very own gradients

**Comment by Sebastianroczz** [comment]
yeah but like do i change the --hackground-primary part like all -- if so what do I change it to?

**Comment by DaBluLite** [comment]
`--nitrolike-profile-primary` and `--nitrolike-profile-secondary` are colors, so hsl,hex, and rgb values. `--nitrolike-profile-gradient-default` is a gradient, so [cssgradients.io](https://cssgradients.io) can generate you a gradient for it

**Comment by Sebastianroczz** [comment]
so i add the hex / rgb values after --nitrolike-profile-primary or write like --(here)

**Comment by DaBluLite** [comment]
after

**Comment by DaBluLite** [comment]
if you want the specific gradient from the screenshot, here is the gradient:
```css
:root {
  --nitrolike-profile-gradient-default: linear-gradient(239.16deg,
    hsl(220 calc(var(--saturation-factor, 1)*86.5%) 17.5%/1) 10.39%,
    hsl(238 calc(var(--saturation-factor, 1)*76.4%) 41.6%/1) 26.87%,
    hsl(184 calc(var(--saturation-factor, 1)*78%) 33.9%/1) 48.31%,
    hsl(169 calc(var(--saturation-factor, 1)*60.2%) 32.5%/1) 64.98%,
    hsl(230 calc(var(--saturation-factor, 1)*92.5%) 26.3%/1) 92.5%);
}
```
Put this in your custom css

**Comment by DaBluLite** [comment]
```css
:root {
    --nitrolike-profile-gradient-default: linear-gradient(128.92deg,
    hsl(183 calc(var(--saturation-factor, 1)*86.3%) 20.2%/1) 3.94%,
    hsl(258 calc(var(--saturation-factor, 1)*89.8%) 23.3%/1) 26.1%,
    hsl(298 calc(var(--saturation-factor, 1)*90.9%) 17.3%/1) 39.82%,
    hsl(265 calc(var(--saturation-factor, 1)*100%) 33.3%/1) 56.89%,
    hsl(207 calc(var(--saturation-factor, 1)*75.5%) 25.4%/1) 76.45%);
}
```
here is the correct one
